services:

  ###############################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./project_datasets/datasets:/app/mounted_datasets
    environment:
      - PYTHONUNBUFFERED=1
  ###############################

  ###############################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    user: "node" 
  ###############################

  ###############################
  # redis:
  #  image: redis:latest
  #  ports:
  #    - "6379:6379"
  ###############################
